parameters:
  - name: Environment
    type: string
    values:
     - uat
     - test
     - prod

trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Auto
    condition: and(succeeded(), eq('${{ parameters.Environment }}', ' ') )
    jobs:
  # - job: Prod
  #   displayName: Prod Automation Run
  #   steps:
  #     - template: pipelines/templates/base-template.yml
  #       parameters:
  #         TestRunTitle: Apigee Automation Run Report
  #         #SlackWebhookUrl: https://hooks.slack.com/services/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
  #         SlackWebhookUrl: https://hooks.slack.com/services/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
  #         ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
  #         Profile: prod
  #         RunEnv: prod
  #   condition:
    - job: Uat
      displayName: Uat Automation Run
      steps:
      - script: |
          echo "Setting up delay for the job"
          echo ${{ parameters.Environment }}
      - template: pipelines/templates/base-template.yml
        parameters:
          TestRunTitle: Apigee Automation Run Report
          #SlackWebhookUrl: https://hooks.slack.com/services/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
          SlackWebhookUrl: https://hooks.slack.com/services/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
          ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
          Profile: regression
          RunEnv: ${{ parameters.Environment }}
   
    - job: Test
      displayName: Test Automation Run
      steps:
      - script: |
          echo "Setting up delay for the job"
          sleep 10m
      - template: pipelines/templates/base-template.yml
        parameters:
          TestRunTitle: Apigee Automation Run Report
          #SlackWebhookUrl: https://hooks.slack.com/services/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
          SlackWebhookUrl: https://hooks.slack.com/services/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
          ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
          Profile: regression
          RunEnv: test

  - stage: Manual
    jobs:
    - job: ManualRun
      displayName: Manual Automation Run
      steps:
      - script: |
          echo "Setting up delay for the job"
          echo ${{ parameters.Environment }}
      - template: pipelines/templates/base-template.yml
        parameters:
          TestRunTitle: Apigee Automation Run Report
          #SlackWebhookUrl: https://hooks.slack.com/services/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
          SlackWebhookUrl: https://hooks.slack.com/services/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
          ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
          Profile: regression
          RunEnv: ${{ parameters.Environment }}
 
schedules:
  - cron: "10 23 * * Mon-Fri"
    displayName: Morning build (starts at 9:10AM)
    branches:
      include:
        - develop
    always: true

  - cron: "10 04 * * Mon-Fri"
    displayName: Afternoon build (starts at 2:10PM)
    branches:
      include:
        - develop
    always: true




