parameters:
- name: RunEnv
  type: string
  default: uat
  values:
    - uat
    - test

trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Test
    displayName: Test Automation Run
    steps:
      - template: pipelines/templates/base-template.yml
        parameters:
          TestRunTitle: Apigee Automation Run Report
          SlackWebhookUrl: https://hooks.slack.com/services/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
          ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
          RunEnv: test

  - job: Uat
    displayName: Uat Automation Run
    steps:
      - script: |
          echo "Setting up delay for the next job"
          sleep 10m
      - template: pipelines/templates/base-template.yml
        parameters:
          TestRunTitle: Apigee Automation Run Report
          SlackWebhookUrl: https://hooks.slack.com/services/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
          ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
          RunEnv: uat


schedules:
  - cron: "10 23 * * Mon-Fri"
    displayName: Morning build (starts at 9:10AM)
    branches:
      include:
        - develop
    always: true

  - cron: "10 04 * * Mon-Fri"
    displayName: Afternoon build (starts at 2:10PM)
    branches:
      include:
        - develop
    always: true



