trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Test
    displayName: Test Automation Run
    steps:
      - template: pipelines/templates/base-template.yml
        parameters:
          TestRunTitle: Apigee Automation Run Report
          SlackWebhookUrl: https://hooks.slack.com/services/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
          ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
          RunEnv: test

  - job: Uat
    displayName: Uat Automation Run
    steps:
      - script: |
          echo "Setting up delay for the next job"
          sleep 10m
      - template: pipelines/templates/base-template.yml
        parameters:
          TestRunTitle: Apigee Automation Run Report
          SlackWebhookUrl: https://hooks.slack.com/services/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
          ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
          RunEnv: uat


schedules:
  - cron: "10 23 * * *"
    displayName: Trigger automation regression run at 9:10AM
    branches:
      include:
        - azure-pipelines
    always: true

  - cron: "10 04 * * *"
    displayName: Trigger automation regression run at 2:10PM
    branches:
      include:
        - azure-pipelines
    always: true



