parameters:
  - name: triggerEnv
    type: string
    default: test
    values:
      - uat
      - test
      - prod

trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  # - job: Prod
  #   displayName: Prod Automation Run
  #   steps:
  #     - template: pipelines/templates/base-template.yml
  #       parameters:
  #         TestRunTitle: Apigee Automation Run Report
  #         SlackWebhookUrl: https://hooks.slack.com/services/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
  #         ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
  #         Profile: prod
  #         RunEnv: prod

  - job: Uat
    displayName: Uat Automation Run
    steps:
      - script: |
          echo "Setting up delay for the job"
          sleep 10s
          echo "parameters=="
          echo ${{ parameters.triggerEnv }}
          echo "variable="
      - template: pipelines/templates/base-template.yml
        parameters:
          TestRunTitle: Apigee Automation Run Report
          #SlackWebhookUrl: https://hooks.slack.com/services/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
          SlackWebhookUrl: https://hooks.slack.com/services/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
          ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
          Profile: regression
          RunEnv: uat
    condition: and(succeededOrFailed(), ne('${{ parameters.triggerEnv }}', ''))


  - job: Test
    displayName: Test Automation Run
    steps:
      - script: |
          echo "parameters=="
          echo ${{ parameters.triggerEnv }}
          echo "variable="
          $url = "https://dev.azure.com/{organization}/{project}/_apis/build/builds/{buildId}?api-version=5.1"
          $buildPipeline= Invoke-RestMethod -Uri $url -Headers @{   
          Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
          } -Method Get
          echo $url
          $starttime= $buildPipeline.startTime
          echo "start time --- "
          echo $starttime
      - template: pipelines/templates/base-template.yml
        parameters:
          TestRunTitle: Apigee Automation Run Report
          #SlackWebhookUrl: https://hooks.slack.com/services/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
          SlackWebhookUrl: https://hooks.slack.com/services/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
          ClusterURL: https://wowuatmobileautoreports.z8.web.core.windows.net
          Profile: regression
          RunEnv: test
    condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', ''))
    
schedules:
  - cron: "10 23 * * Mon-Fri"
    displayName: Morning build (starts at 9:10AM)
    branches:
      include:
        - develop
    always: true

  - cron: "10 04 * * Mon-Fri"
    displayName: Afternoon build (starts at 2:10PM)
    branches:
      include:
        - develop
    always: true




