parameters:
  - name: triggerEnv
    type: string
    default: all
    values:
      - uat
      - test
      - prod
      - all

trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Auto
    # Job schedules are managed --> https://wowonline.visualstudio.com/Mobile/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1603&view=Tab_Triggers
    jobs:
      - job: Prod_Trader
        steps:
          - template: pipelines/templates/base-template.yml
            parameters:
              TestRunTitle: Prod_Trader Automation Run Report
              Profile: Prod_trader
              RunEnv: prod
        condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', 'all'))

      - job: Uat_Trader
        steps:
          - script: |
              echo "Setting up delay for the job"
              sleep 10m
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              TestRunTitle: Uat_Trader Automation Run Report
              Profile: regression_trader
              RunEnv: uat
        condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', 'all'))

      - job: Test_Trader
        steps:
          - script: |
              echo "Setting up delay for the job"
              sleep 10m
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              TestRunTitle: Test_Trader Automation Run Report
              Profile: regression_trader
              RunEnv: test
        condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', 'all'))

  - stage: Manual

    jobs:
      - job: Manual
        variables:
          ${{ if eq(parameters.triggerEnv, 'prod') }}:
            TriggeredProfile: Prod_trader
          ${{ if eq(parameters.triggerEnv, 'uat') }}:
            TriggeredProfile: regression_trader
          ${{ if eq(parameters.triggerEnv, 'test') }}:
            TriggeredProfile: regression_trader
        displayName: Manual Automation Run
        steps:
          - script: |
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              TestRunTitle: Trader Automation Run Report
              Profile: ${{variables.TriggeredProfile}}
              RunEnv: ${{ parameters.triggerEnv }}
        condition: and(succeededOrFailed(), ne('${{ parameters.triggerEnv }}', 'all'))