parameters:
  - name: triggerEnv
    type: string
    default: all
    values:
      - uat
      - test
      - prod
      - all

trigger:
  none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Auto
    # Jobs schedules are managed --> https://wowonline.visualstudio.com/Mobile/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1604&view=Tab_Triggers
    jobs:
      - job: Prod_rewards
        steps:
          - template: pipelines/templates/base-template.yml
            parameters:
              TestRunTitle: Prod_rewards Automation Run Report
              Profile: Prod_rewards
              RunEnv: prod
        condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', 'all'))

      - job: Uat_Metis
        steps:
          - script: |
              echo "Setting up delay for the job"
              sleep 10m
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              TestRunTitle: Uat_Rewards Automation Run Report
              Profile: regression_rewards
              RunEnv: uat
        condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', 'all'))

      - job: Test_Rewards
        steps:
          - script: |
              echo "Setting up delay for the job"
              sleep 10m
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              TestRunTitle: Test_Rewards Automation Run Report
              Profile: regression_rewards
              RunEnv: test
        condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', 'all'))

  - stage: Manual
    jobs:
      - job: Manual
        displayName: Manual Automation Run
        variables:
          ${{ if eq(parameters.triggerEnv, 'prod') }}:
            TriggeredProfile: Prod_rewards
          ${{ if eq(parameters.triggerEnv, 'uat') }}:
            TriggeredProfile: regression_rewards
          ${{ if eq(parameters.triggerEnv, 'test') }}:
            TriggeredProfile: regression_rewards
        steps:
          - script: |
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              TestRunTitle: Rewards Automation Run Report
              Profile: ${{variables.TriggeredProfile}}
              RunEnv: ${{ parameters.triggerEnv }}
        condition: and(succeededOrFailed(), ne('${{ parameters.triggerEnv }}', 'all'))