parameters:
  - name: triggerEnv
    displayName: Run Environment
    type: string
    default: test
    values:
      - uat
      - test
      - all

trigger:
  none

pool: 'wlx-ubuntu1804'

stages:
  - stage: Auto
    # Jobs schedules are managed --> https://wowonline.visualstudio.com/Mobile/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1604&view=Tab_Triggers
    jobs:
      - job: Prod_Rewards
        steps:
          - script: |
              echo "Setting up delay for the job"
              sleep 10m
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              SlackWebHookUrl: https://hooks.slack.com/services/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
              TestRunTitle: Prod Rewards Automation Run Report
              Profile: regression_rewards
              RunEnv: prod
              Service: rewards
        condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', 'all'))


      - job: Uat_Rewards
        steps:
          - script: |
              echo "Setting up delay for the job"
              sleep 10m
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              SlackWebHookUrl: https://hooks.slack.com/services/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
              TestRunTitle: Uat Rewards Automation Run Report
              Profile: regression_rewards
              RunEnv: uat
              Service: rewards
        condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', 'all'))

      - job: Test_Rewards
        steps:
          - script: |
              echo "Setting up delay for the job"
              sleep 10m
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              SlackWebHookUrl: https://hooks.slack.com/services/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
              TestRunTitle: Test Rewards Automation Run Report
              Profile: regression_rewards
              RunEnv: test
              Service: rewards
        condition: and(succeededOrFailed(), eq(variables['Build.Reason'], 'Schedule'))


  - stage: Manual
    jobs:
      - job: Manual
        displayName: Manual Automation Run
        steps:
          - script: |
              echo ${{ parameters.triggerEnv }}
          - template: pipelines/templates/base-template.yml
            parameters:
              SlackWebHookUrl: https://hooks.slack.com/services/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
              TestRunTitle: Rewards Automation Run Report
              Profile: regression_rewards
              RunEnv: ${{ parameters.triggerEnv }}
              Service: rewards
        condition: and(succeededOrFailed(), in(variables['Build.Reason'], 'Manual','IndividualCI','PullRequest'))