parameters:
  - name: triggerEnv
    displayName: Run Environment
    type: string
    default: all
    values:
      - uat
      - test
      - prod
      - all

trigger:
  none

pool: 'wlx-ubuntu1804'

stages:
  - stage: Auto
    # Job schedules are managed --> https://wowonline.visualstudio.com/Mobile/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1602&view=Tab_Triggers

    jobs:
      - job: Uat_ScanGo
        steps:
          - script: |
              echo "Setting up delay for the job"
              sleep 10m

          - template: pipelines/templates/base-template.yml
            parameters:
              SlackWebHookUrl: $(scanNGo_slackWebHookUrl)
              TestRunTitle: Uat Scan&Go Automation Run Report
              Profile: smoke_scango
              RunEnv: uat
              Service: scango
        condition: and(succeededOrFailed(), eq('${{ parameters.triggerEnv }}', 'all'), eq(variables['Build.Reason'], 'Schedule'))


  - stage: Manual
    jobs:
      - job: Manual
        displayName: Manual Automation Run
        variables:
          ${{ if eq(parameters.triggerEnv, 'prod') }}:
            TriggeredProfile: prod_scango
            TriggeredEnv: ${{ parameters.triggerEnv }}
          ${{ if eq(parameters.triggerEnv, 'uat') }}:
            TriggeredProfile: smoke_scango
            TriggeredEnv: ${{ parameters.triggerEnv }}
          ${{ if eq(variables['Build.Reason'], 'IndividualCI') }}:
            TriggeredProfile: smoke_scango
            TriggeredEnv: uat
          ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
            TriggeredProfile: smoke_scango
            TriggeredEnv: uat
        steps:
          - script: |
              echo $(Build.Reason)
              echo ${{variables.TriggeredEnv}}
          - template: pipelines/templates/base-template.yml
            parameters:
              SlackWebHookUrl: $(scanNGo_slackWebHookUrl)
              TestRunTitle: Scan&Go Automation Run Report
              Profile: ${{variables.TriggeredProfile}}
              RunEnv: ${{variables.TriggeredEnv}}
              Service: scango
        condition: and(succeededOrFailed(), in(variables['Build.Reason'], 'Manual','IndividualCI','PullRequest'))

